### PR TITLE
Feature user profile

### PR DESCRIPTION
**Pull request by jsvcycling**

### CODE REVIEW

**Comment by sulekhadahiya** [comment]
This branch was not ready for merge...I am still working on it. It will break master branch. Master branch needs Java version and other dependencies to be upgraded.

**Comment by Jsvcycling** [comment]
@sulekhadahiya I fixed the conflicts, it's building properly in master, it's just missing AWS keys. You can keep working on this branch and I'll re-merge it once you're done.

**Comment by sulekhadahiya** [comment]
But we should stay on Java 11 not on Java 8. I am planning to deploy it in docker container and Java 8 is not good for that.

**Comment by Jsvcycling** [comment]
I'm working on upgrading master to 11 right now so we'll be able to continue on 11. I just wanted to make sure the branches were compatible otherwise.

**Comment by sulekhadahiya** [comment]
Good...Java 8 is ready obsolete

**Comment by Jsvcycling** [comment]
Master is now on Java 11. I had to fix a few deprecation warnings from my code.

**Pull request merged**
